import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper"; 
import ProviderOfParallax from "@/providers/ProviderOfParallax";

import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Alliance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <ProviderOfParallax>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ClientWrapper>{children}</ClientWrapper>
            <Toaster
              toastOptions={{
                className: "",
                style: {
                  border: "1px solid #87ceeb",
                  padding: "16px",
                  color: "black",
                },
              }}
            />
          </body>
        </ProviderOfParallax>
      </ClerkProvider>
    </html>
  );
}
